[package]
name = "twitch-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
<<<<<<< HEAD
=======
serde = { version = "1.0.214", features = ["derive"] }
tokio = "1.41.1"
reqwest = "0.12.9"
>>>>>>> f5d9c85 (initial commit)
